LOCAL_SSD="/home/tmyn/moe/hdd/checkpoints/runs11/transformer_pile-00_0_exp7"
CHECKPOINT="checkpoint_last.pt"
MODEL_SHARED_FOLDER="/home/tmyn/moe/hdd/checkpoints/runs11/transformer_pile-00_0_exp7"
BPE_DIR="data-bin/pile-00"
TASK="streaming_diffusion_language_modeling"